### ISSUE TITLE
Support for Laravel 7/8

### ISSUE THREAD

**Issue by sheinfeld** [InputOutputZ/AzureTran#3]
Hi,

Would I be possible to add support to Laravel 7+ (8)?

Thank you so much!

**Comment by InputOutputZ** [comment]
Hi,

If your question was asking if it's possible for yourself to add support, yes you can.

If requesting support, then I have tested in Laravel 6.4 only yet, Laravel didn’t change the way packages work in 7/8 so it should work, except with guzzlehttp dependancy, in the package it should load the latest one laravel framework uses, which can be retrieved from laravel composer.json and updated in the package composer.json and running composer upgrade command should update it, note it will update other laravel packages as well along and if want to update the package only run: composer require azuretran/translate.

Anyhow, I will be releasing new version with enhanced functions, optimising translation queries as well as better exception handling and Laravel 7, 8 fully supported, around mid of October, and if you can't wait until then, then I advise to test yourself, and I will be happy to help whenever I can in case bugs found in current version.

You are welcome.

Zakaria.

**Comment by sheinfeld** [comment]
Thanks!

**Comment by InputOutputZ** [comment]
I do apologise for the late update. I've just had the chance now to publish the release.

Any feedback is very much appreciated.

With thanks.

Zakaria.
